### ISSUE TITLE
 Attempt to invoke virtual method 'int me.littlecheesecake.croplayout.model.ScalableBox.getY1()' on a null object reference

### ISSUE THREAD

**Issue by dijiubuzhan** [visenze/productcat-sdk-android#25]
在点击标签更新box位置时出现异常，下面是我调用代码
 editableImage.setBox(getDetectionBox(productType.getBox()));
                    editPhotoView.initView(EditPhotoActivity.this, editableImage);

错误日志：
07-23 20:39:57.976 13583-13583/com.elephanttek.aishopping E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.elephanttek.aishopping, PID: 13583
    java.lang.NullPointerException: Attempt to invoke virtual method 'int me.littlecheesecake.croplayout.model.ScalableBox.getY1()' on a null object reference
        at me.littlecheesecake.croplayout.SelectionView.drawShadow(SelectionView.java:142)
        at me.littlecheesecake.croplayout.SelectionView.onDraw(SelectionView.java:133)
        at android.view.View.draw(View.java:17094)
        at android.view.View.updateDisplayListIfDirty(View.java:16076)
        at android.view.View.draw(View.java:16860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3563)
        at android.view.View.draw(View.java:17097)
        at android.view.View.updateDisplayListIfDirty(View.java:16076)
        at android.view.View.draw(View.java:16860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3563)
        at android.view.View.updateDisplayListIfDirty(View.java:16071)
        at android.view.View.draw(View.java:16860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3563)
        at android.view.View.draw(View.java:17097)
        at android.view.View.updateDisplayListIfDirty(View.java:16076)
        at android.view.View.draw(View.java:16860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
        at com.sothree.slidinguppanel.SlidingUpPanelLayout.drawChild(SlidingUpPanelLayout.java:1204)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3563)
        at android.view.View.draw(View.java:17097)
        at com.sothree.slidinguppanel.SlidingUpPanelLayout.draw(SlidingUpPanelLayout.java:1257)
        at android.view.View.updateDisplayListIfDirty(View.java:16076)
        at android.view.View.draw(View.java:16860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3563)
        at android.view.View.updateDisplayListIfDirty(View.java:16071)
        at android.view.View.draw(View.java:16860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3563)
        at android.view.View.updateDisplayListIfDirty(View.java:16071)
        at android.view.View.draw(View.java:16860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3563)
        at android.view.View.updateDisplayListIfDirty(View.java:16071)
        at android.view.View.draw(View.java:16860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3563)
        at android.view.View.draw(View.java:17097)
        at com.android.internal.policy.DecorView.draw(DecorView.java:765)
        at android.view.View.updateDisplayListIfDirty(View.java:16076)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:657)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:663)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:771)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2824)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2632)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2239)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1259)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6341)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
        at android.view.Choreographer.doFrame(Choreographer.java:619)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6162)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by yulu** [comment]
@dijiubuzhan could you please try to upgrade the croplayout library version to 1.1.5 in the demo app's dependencies. The exception should be handled in the latest release.

```
dependencies {
    implementation 'me.littlecheesecake:croplayout:1.1.5'
}
```
